/**
 * Check-Direkt-Sparten als Lead-Produkte.
 *
 * Quelle: Check-Direkt-Lead-Anbieter (https://check-direkt.de). Kuerzel sind
 * bewusst die Original-Codes, damit CSV-Preislisten automatisch matchen.
 *
 * Aenderungen hier wirken sich beim naechsten Container-Start aus
 * (siehe runtime-migrations.ts).
 */
export const CHECK_DIREKT_SPARTEN: ReadonlyArray<readonly [string, string]> = [
  ["B-KV", "Betriebliche Krankenversicherung"],
  ["BRV", "Basisrentenversicherung"],
  ["TiKv-H", "Hunde Krankenversicherung"],
  ["KVB", "Krankenversicherung fuer Beamte"],
  ["Q-AVS", "vorqualifizierte Altersvorsorge"],
  ["Q-BUV", "vorqualifizierte Berufsunfaehigkeitsversicherung"],
  ["Q-KVV", "vorqualifizierte Private Krankenvollversicherung"],
  ["VSH", "Vermoegensschadenhaftpflicht"],
  ["Q-GwS", "vorqualifizierte gewerbliche Sachversicherung"],
  ["Q-RsV", "vorqualifizierte Rechtsschutzversicherung"],
  ["Q-St-Geld", "vorqualifizierte Sterbegeldversicherung"],
  ["AVS", "Altersvorsorge"],
  ["AVS55+", "Altersvorsorge 55+"],
  ["AVS-A", "Altersvorsorge fuer Akademiker"],
  ["AVS-B", "Altersvorsorge fuer Beamte"],
  ["AVS-KAP", "Altersvorsorge mit Kapitalanlage"],
  ["AVSU35", "Altersvorsorge U35"],
  ["Arch-V", "Architektenversicherung"],
  ["Arzt-V", "Aerzteversicherung"],
  ["AUT", "Automatenversicherung"],
  ["BSV", "Bausparvertrag"],
  ["B-HV", "Berufshaftpflichtversicherung"],
  ["Arzt-BHV", "Berufshaftpflichtversicherung fuer Aerzte"],
  ["B-RS", "Berufsrechtsschutz"],
  ["BUV", "Berufsunfaehigkeitsversicherung"],
  ["BUV35+", "Berufsunfaehigkeitsversicherung 35+"],
  ["BUV55+", "Berufsunfaehigkeitsversicherung 55+"],
  ["BAV", "Betriebliche Altersvorsorge"],
  ["BAS", "Betriebsausfallversicherung"],
  ["BHV", "Betriebshaftpflichtversicherung"],
  ["BU", "Betriebsunterbrechungsversicherung"],
  ["KFZ-BMW", "BMW Versicherung"],
  ["BV", "Brillenversicherung"],
  ["BUEV", "Bueroversicherung"],
  ["CYBR", "Cyberversicherung"],
  ["CYBR-G", "Cyberversicherung gewerblich"],
  ["DUV", "Dienstunfaehigkeitsversicherung"],
  ["DaO", "Directors & Officers"],
  ["DD", "Dread Disease"],
  ["EBV", "E-Bike-Versicherung"],
  ["EAV", "Ertragsausfallversicherung"],
  ["ErwerbU", "Erwerbsunfaehigkeitsversicherung"],
  ["ETF-RV", "ETF-Rente"],
  ["ETF-Spar", "ETF-Sparplan"],
  ["FDV", "Fahrradversicherung"],
  ["F-RS", "Familienrechtsschutz"],
  ["KFZ-F", "Ferrariversicherung"],
  ["FIV", "Flottenversicherung"],
  ["FZV", "Flugzeugversicherung"],
  ["FB-V", "Freiberuflerversicherung"],
  ["Gas", "Gasvergleich"],
  ["GA", "Geldanlage"],
  ["GF-V", "Geschaeftsfuehrer Versicherung"],
  ["GIV", "Geschaeftsinhaltsversicherung"],
  ["gKV", "gesetzliche Krankenversicherung"],
  ["RsVG", "gewerbliche Rechtsschutzversicherung"],
  ["GwS", "gewerbliche Sachversicherung"],
  ["GLS", "Glasversicherung"],
  ["GUV", "Gruppenunfallversicherung"],
  ["HRV", "Hausratversicherung"],
  ["HuHa", "Hunde Haftpflichtversicherung"],
  ["Hunde-OP", "Hunde-OP-Versicherung"],
  ["Immo", "Immobilien"],
  ["IF", "Immobilienfinanzierung"],
  ["IDV", "Industrieversicherung"],
  ["Ing-V", "Ingenieurversicherung"],
  ["JHV", "Jagdhaftpflichtversicherung"],
  ["KFZ-J", "Jaguarversicherung"],
  ["KAP", "Kapitalanlageimmobilie"],
  ["K-LV", "Kapitalbildende Lebensversicherung"],
  ["KAT", "Katzenversicherung"],
  ["KFZ-TK", "KFZ Kredit"],
  ["KFZ-VK", "KFZ Vollkasko"],
  ["KFZ-O", "KFZ-Oldtimer Versicherung"],
  ["KSP", "Kindersparplan"],
  ["Kombi", "Kombi-Sachversicherung"],
  ["KFZ", "Kraftfahrzeugversicherung"],
  ["KRV", "Krebsversicherung"],
  ["KUV", "Kunstversicherung"],
  ["KFZ-L", "Lamborghiniversicherung"],
  ["KFZ-LR", "Land Rover Versicherung"],
  ["LWV", "Landwirtschaftsversicherung"],
  ["LV", "Lebensversicherung"],
  ["Leh-V", "Lehrerversicherung"],
  ["MRS", "Manager-Rechtsschutzversicherung"],
  ["MBV", "Maschinenbruchversicherung"],
  ["MV", "Maschinenversicherung"],
  ["MFHV", "Mehrfamilienhausversicherung"],
  ["KFZ-AMG", "Mercedes-AMG Versicherung"],
  ["M-RS", "Mieterrechtsschutz"],
  ["MKV", "Mietkautionsversicherung"],
  ["MPV", "Mopedversicherung"],
  ["MRV", "Motorradversicherung"],
  ["KFZ-N", "Neuwagenversicherung"],
  ["PfV", "Pferdeversicherung"],
  ["PV-V", "Photovoltaikversicherung"],
  ["KVV-EL", "PKV Elite"],
  ["PKV-Zahn", "PKV-Zahn"],
  ["KFZ-P", "Porscheversicherung"],
  ["PRA", "Praxisausfallversicherung"],
  ["PHI", "Private Health Insurance"],
  ["PHV", "private Haftpflichtversicherung"],
  ["KVV", "Private Krankenvollversicherung"],
  ["KVV-L", "Private Krankenvollversicherung (L)"],
  ["KVV-UL", "Private Krankenvollversicherung (UL)"],
  ["KV55+", "Private Krankenversicherung 55+"],
  ["KV60+", "Private Krankenversicherung 60+"],
  ["KVV-M", "Private Krankenvollversicherung Medium"],
  ["PK", "Privatkredit"],
  ["P-HV", "Produkthaftpflichtversicherung"],
  ["PK-V", "Prokuristen Versicherung"],
  ["Psy-V", "Psychotherapeutenversicherung"],
  ["RA-V", "Rechtsanwaltversicherung"],
  ["RsV", "Rechtsschutzversicherung"],
  ["RSV-R", "Rechtsschutzversicherung (R)"],
  ["RsV-L", "Rechtsschutzversicherung Light"],
  ["RKV", "Reisekrankenversicherung"],
  ["RTT", "Reiseruecktrittsversicherung"],
  ["RSE", "Reiseversicherung"],
  ["RRV", "Riesterrentenversicherung"],
  ["RLV", "Risikolebensversicherung"],
  ["RWS", "Rueckwechsler"],
  ["RueRV", "Rueruprentenversicherung"],
  ["SFV", "Schliessfachversicherung"],
  ["SV-V", "Schluesselverlustversicherung"],
  ["SRV", "Sofort Rentenversicherung"],
  ["Sold-V", "Soldatenversicherung"],
  ["Sport-UV", "Sportunfallversicherung"],
  ["St-Geld", "Sterbegeldversicherung"],
  ["St-Geld-L", "Sterbegeldversicherung Light"],
  ["StB-V", "Steuerberaterversicherung"],
  ["Strom", "Stromvergleich"],
  ["StromG", "Stromvergleich Gewerbe"],
  ["StromGas", "Stromvergleich und Gasvergleich"],
  ["KFZ-T", "Teslaversicherung"],
  ["TRV", "Transportversicherung"],
  ["Unv", "Unfallversicherung"],
  ["VAL", "Valorenversicherung"],
  ["V-HV", "Veranstaltungshaftpflichtversicherung"],
  ["V-RS", "Verkehrsrechtsschutz"],
  ["VM-V", "Vermieter Versicherung"],
  ["RsVV", "Vermieterrechtsschutzversicherung"],
  ["VVW", "Vermoegensverwaltung"],
  ["VWL", "Vermoegenswirksame Leistungen"],
  ["VRS", "Vertragsrechtsschutzversicherung"],
  ["VSV", "Vertrauensschadenversicherung"],
  ["KFZ-V", "Volvo Versicherung"],
  ["Q-BV", "vorqualifizierte Brillenversicherung"],
  ["WKV", "Warenkreditversicherung"],
  ["WGV", "Wohngebaeudeversicherung"],
  ["WMV", "Wohnmobilversicherung"],
  ["YBV", "Yacht-/Bootsversicherung"],
  ["ZA-V", "Zahnaerzteversicherung"],
  ["ZV-Zahn", "Zahnzusatzversicherung"],
  ["ZV-Zahn-L", "Zahnzusatzversicherung light"],
] as const;

/**
 * Mapping fuer bestehende Lead-Produkte (alte 22er-Liste) auf das neue
 * Check-Direkt-Kuerzel. Wird beim Container-Start einmalig auf alle Sparten
 * angewendet, bei denen `kuerzel` noch leer ist. Verhindert Duplikate beim
 * spaeteren Seed.
 */
export const LEGACY_KUERZEL_MAP: Record<string, string> = {
  "Betriebshaftpflicht": "BHV",
  "Beratung": "BER",
  "Finanzierung": "IF",
  "Firmenrechtsschutzversicherung": "RsVG",
  "Firmenversicherung": "GIV",
  "Flottenversicherung": "FIV",
  "Haftpflichtversicherung": "PHV",
  "Hausratversicherung": "HRV",
  "Hundeversicherung": "TiKv-H",
  "KFZ-Versicherung": "KFZ",
  "Krankenzusatzversicherung": "KVV",
  "Pferdeversicherung": "PfV",
  "Rechtsschutzversicherung": "RsV",
  "Sterbegeldversicherung": "St-Geld",
  "Unfallversicherung": "Unv",
  "Vermögensschadenhaftpflicht": "VSH",
  "Wohngebäudeversicherung": "WGV",
  "Zahnzusatzversicherung": "ZV-Zahn",
  "Private Krankenversicherung": "KVV",
  "Private Pflegeversicherung": "PPV",
  "Firmeninhaltsversicherung": "GIV",
  "Cyberschutzversicherung": "CYBR",
};
